fastio: ex13q1.c
	gcc -Wall -Wextra -std=c99 -DFASTIO -o fastio ex13q1.c

easyio: ex13q1.c
	gcc -Wall -Wextra -std=c99 -DEASYIO -o easyio ex13q1.c

clean:
	rm -f args_3 input_3 ex13q1 output_3 student_3 easyio fastio
